export const Paths = {
    Home: '/',
    Catalog: '/catalog',
    BooksByCategory: '/catalog/:categoryId/:categoryName',
    Bestsellers: '/bestsellers',
    BookDetails: 'catalog/book/:bookId/details',
    ShoppingBasket: '/shopping-basket',
    Checkout: '/checkout',
    OrderSuccess: '/order-success/:orderNumber',
    Login: '/login',
    Register: '/register',
    Logout: '/logout',
    Profile: '/profile',
    NotFound: '*',
}